options:
  logging: CLOUD_LOGGING_ONLY
  # Alternatively, you can specify a logs bucket or set the default_logs_bucket_behavior
  # logsBucket: 'gs://your-logs-bucket'
  # defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: ['cicd.sh', '$PROJECT_ID', '${_VIEWS_DIR}']
  env: 
    - 'project_id=eu-medico-residente' 
    - 'views_dir=views'
timeout: 1200s
substitutions:
  _VIEWS_DIR: views
# Optionally specify the service account if needed
# serviceAccount: 'projects/YOUR_PROJECT_ID/serviceAccounts/YOUR_SERVICE_ACCOUNT_EMAIL'
