steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: ['cicd.sh', '$PROJECT_ID', '${_VIEWS_DIR}']
  env: 
    - 'project_id=eu-medico-residente' 
    - 'views_dir=views'
timeout: 1200s
substitutions:
  _VIEWS_DIR: views
serviceAccount: 'projects/eu-medico-residente/serviceAccounts/eu-medico-residente@appspot.gserviceaccount.com'
